### ISSUE TITLE
Permission denied on Configuration tab for Administrator

### ISSUE THREAD

**Issue by marc-cabocel** [Nanocloud/nanocloud#182]
=== Version ===
- v2.0.0-rc1

=== Steps to reproduce ===
- clone nanocloud repo. checkout tag 2.0.0-rc1
- Use a standard windows 2012 ami as AWS image
- docker-compose build, docker-compose up -d to install and start NC
- Connect to the platform as an admin
- publish google chrome (install it on the VM, save the image and onboard the app)
- Now make sure to clean your pool and use a new VM
- Go to Applications & click chrome
- Chrome should appear after 10/20s, then click the home button.
- Try to go to Configuration tab

=== Expected Result ===
- It's working

=== Actual Result ===
- It is not working. A pop-up message shows "Permission Denied"

**Comment by dynamiccast** [comment]
I have been able to reduce the number of steps to reproduce the bug.
Turns out, publishing an application is not related with the issue.

Set a session duration to 60 seconds
As admin connect to the VDI
Click home and go back to applications
Wait for the broker to deallocate current machine
Try to go to configuration
