### ISSUE TITLE
Add Windows auto-login to shorten the login delay

### ISSUE THREAD

**Issue by Erfane** [Nanocloud/nanocloud#319]
When starting an application or a desktop, if the user is not already logged in, Windows will take some time to process the login. We should not show the login process to the user to shorten the login process :
- if the virtual machine is already started
- if the user is logging in for the first time on the virtual machine

**Comment by dynamiccast** [comment]
Profits from auto login users in the virtual environment are unclear.
This is something already achieved in the default image created for the QEMU driver: https://github.com/Nanocloud/nanocloud/blob/master/packer/floppy/windows-2012-standard-amd64/Autounattend.xml#L120
Here the password is hard coded, which is fine because the QEMU image is only suitable for development.
However, auto login the user will require manipulation with the unencrypted Windows password. Besides security implication this means if the Windows' password changes the behavior of what would be developed for this feature is undefined.

In my opinion we need to consider this feature first https://github.com/Nanocloud/nanocloud/issues/318 prior to any change that would comprime the synchronization between Window's accounts and Nanocloud.

Finally, the model of one user per machine in Nanocloud may be subject to change. What if we develop a model using RDS that would bring multiple user in one VM ?

**Comment by dynamiccast** [comment]
This issue has not received any new input since my last comment. Feel free to reopen it if you find more ideas to implement this.
